### ISSUE TITLE
Predicted object number less than GT object number

### ISSUE THREAD

**Issue by guohengkai** [davisvideochallenge/davis2017-evaluation#1]
When the predicted object number is less than GT object number, this line will lead to a error:
https://github.com/davisvideochallenge/davis2017-evaluation/blob/master/davis2017/evaluation.py#L30

So I think the one-hot conversion for result masks should use the GT object number instead of the result object number.

Thanks.

**Comment by guohengkai** [comment]
Or you can fill the missing object masks with zero.

**Comment by scaelles** [comment]
Thanks for pointing this out, it should be now fixed.
