### ISSUE TITLE
About temporal stability 

### ISSUE THREAD

**Issue by eastOffice** [davisvideochallenge/davis2017-evaluation#2]
Hi there,

I noticed that since davis 2017, temporal stability has not been one of the evaluation metrics. Would you mind telling the reason? Since it seems to be an important aspect and a numeric metric is desired.

Thanks

**Comment by eastOffice** [comment]
I see the reason [here](https://arxiv.org/pdf/1704.00675.pdf) now. However, temporal stability is only supported in davis16's repo, could you support it in this version?

**Comment by scaelles** [comment]
Hello,
As stated in the link that you mentioned, temporal stability is not easy to measure when objects in the videos undergo severe occlusions. In DAVIS16, the measure was only computed on a subset of video sequences for that reason and we decided to drop it in DAVIS17. This repository only supports DAVIS17 evaluation and therefore including the temporal stability measure is not in our plans. If you would like to compute it, I would suggest that you use the [matlab](https://github.com/davisvideochallenge/davis-matlab) repository.
