### ISSUE TITLE
Could this code be used for the evaluation of Davis-2016? 

### ISSUE THREAD

**Issue by XavierCHEN34** [davisvideochallenge/davis2017-evaluation#3]
if i modify this code a little, like changing the val.txt and annotations format to Davis2016, could i use this code directly for the evaluation of davis 2016?  I just want to know if  the implementation details of J/F are exactly the same with 2016 version.
Thx

**Comment by scaelles** [comment]
Hello,
The implementation details for J and F are the same that the ones used for DAVIS 2016. However, I would strongly recommend that you double check your final result using the [Matlab](https://github.com/davisvideochallenge/davis-matlab) or [Python](https://github.com/davisvideochallenge/davis) versions released for DAVIS 2016 to verify that your modifications are correct.
