### ISSUE TITLE
can you publish the unsupervised results on test-dev of davis2019 dataset by using RVOS code? 

### ISSUE THREAD

**Issue by JanySunny** [davisvideochallenge/davis2017-evaluation#5]

**Comment by JanySunny** [comment]
Hello,
Can you publish the unsupervised results on test-dev of davis2019 dataset by using rvos code? I test the unsupervised test-dev set of Davis2019 using roves code, but the score is lower 2 points than the values published in [the Davis 2019 challenge paper](https://arxiv.org/abs/1905.00737). It will be better if release the test code for Davis2019 unsupervised test-dev. Thank you.

**Comment by scaelles** [comment]
Hello Jany,
You can find all the RVOS results in the semisupervised and unsupervised setting for val and for test-dev in https://davischallenge.org/results/2017/rvos.zip
Let me know if you have any further questions.
