### ISSUE TITLE
use cases for evaluation code in different repos

### ISSUE THREAD

**Issue by InnovArul** [davisvideochallenge/davis2017-evaluation#6]
Hi, I see that there are multiple repos available for DAVIS evaluation.
Could you please clarify which is the latest/recommended to use?

For example, the two relevant repos are:

https://github.com/davisvideochallenge/davis-2017
https://github.com/davisvideochallenge/davis2017-evaluation

**Comment by scaelles** [comment]
Hello,

The latest version is the one used to evaulate the challenges (DAVIS 2017):
https://github.com/davisvideochallenge/davis2017-evaluation

They should both give you the same result though.

For DAVIS 2016, you should use:
[Python](https://github.com/davisvideochallenge/davis)
[Matlab](https://github.com/davisvideochallenge/davis-matlab)

Let me know if you have any further questions.

**Comment by InnovArul** [comment]
Thanks a lot for the clarification. I will check them out.
