### ISSUE TITLE
Unexpected error

### ISSUE THREAD

**Issue by dxlong2000** [davisvideochallenge/davis2017-evaluation#8]
Hi all,

This is my command I run and I got an unexpected error. I change the path to DAVIS correctly.

```
python evaluation_method.py --task semi-supervised --results_path my_results/semi-supervised 
Evaluating sequences for the semi-supervised task...
  0%|                                                    | 0/30 [00:00<?, ?it/s]bike-packing frame 00001 not found!
The frames have to be indexed PNG files placed inside the corespondent sequence folder.
The indexes have to match with the initial frame.
IOError: No such file or directory
  0%|                                                    | 0/30 [00:00<?, ?it/s]
```

Could anyone help me to figure out the problem?

**Comment by longmalongma** [comment]
> Hi all,
> 
> This is my command I run and I got an unexpected error. I change the path to DAVIS correctly.
> 
> ```
> python evaluation_method.py --task semi-supervised --results_path my_results/semi-supervised 
> Evaluating sequences for the semi-supervised task...
>   0%|                                                    | 0/30 [00:00<?, ?it/s]bike-packing frame 00001 not found!
> The frames have to be indexed PNG files placed inside the corespondent sequence folder.
> The indexes have to match with the initial frame.
> IOError: No such file or directory
>   0%|                                                    | 0/30 [00:00<?, ?it/s]
> ```
> 
> Could anyone help me to figure out the problem?

Have you solved this problem?I also met this problem.

@albertomontesg @

**Comment by longmalongma** [comment]
> Hi all,
> 
> This is my command I run and I got an unexpected error. I change the path to DAVIS correctly.
> 
> ```
> python evaluation_method.py --task semi-supervised --results_path my_results/semi-supervised 
> Evaluating sequences for the semi-supervised task...
>   0%|                                                    | 0/30 [00:00<?, ?it/s]bike-packing frame 00001 not found!
> The frames have to be indexed PNG files placed inside the corespondent sequence folder.
> The indexes have to match with the initial frame.
> IOError: No such file or directory
>   0%|                                                    | 0/30 [00:00<?, ?it/s]
> ```
> 
> Could anyone help me to figure out the problem?

@Long-Xuan-Do Have you solved this problem?I also met this problem.

**Comment by longmalongma** [comment]
> > Hi all,
> > This is my command I run and I got an unexpected error. I change the path to DAVIS correctly.
> > ```
> > python evaluation_method.py --task semi-supervised --results_path my_results/semi-supervised 
> > Evaluating sequences for the semi-supervised task...
> >   0%|                                                    | 0/30 [00:00<?, ?it/s]bike-packing frame 00001 not found!
> > The frames have to be indexed PNG files placed inside the corespondent sequence folder.
> > The indexes have to match with the initial frame.
> > IOError: No such file or directory
> >   0%|                                                    | 0/30 [00:00<?, ?it/s]
> > ```
> > 
> > 
> > Could anyone help me to figure out the problem?
> 
> @Long-Xuan-Do Have you solved this problem?I also met this problem.

@Long-Xuan-Do Have you solved this problem?

**Comment by scaelles** [comment]
Hello,
Have you tried changing the path to your locally downloaded DAVIS copy in [here](https://github.com/davisvideochallenge/davis2017-evaluation/blob/d34fdef71ce3cb24c1a167d860b707e575b3034c/evaluation_method.py#L11)? 
Also, in order to test that you have the correct folder structure, try to evaluate davis2017-evaluation/results/semi-supervised/osvos.
